baseURL = "https://leroy.baynum.net/"
languageCode = "en-us"
title = "Leroy A. Baynum Jr."

theme = "meghna-hugo"

# Menu
[menu]
    [[menu.nav]]
    name = "About"
    URL = "about"
    weight = 2

    [[menu.nav]]
    name = "Service"
    URL = "services"
    weight = 3

    [[menu.nav]]
    name = "Portfolio"
    URL = "portfolio"
    weight = 4

    [[menu.nav]]
    name = "Team"
    URL = "our-team"
    weight = 5

    [[menu.nav]]
    name = "Pricing"
    URL = "pricing"
    weight = 6

    [[menu.nav]]
    name = "Blog"
    URL = "blog"
    weight = 7

    [[menu.nav]]
    name = "Contact"
    URL = "contact-us"
    weight = 8

# Site params
[params]
home= "Home"
logo = "images/kubernetesLogo42x43.png"
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
# Meta data
description = "A high level view of the inner workings of the mind of Leroy A. Baynum Jr."
author = "Leroy A. Baynum Jr."
# Google Analitycs
googleAnalitycsID = "UA-128737572-2"
custom_css = ["css/custom.css"]

    # Banner Section
    [params.banner]
    enable = true
    bgImage = "images/slider/hero-area2.jpg"
    icon = "tf-ion-social-github"
    heroLogo = "images/icon cloud.png"
    heading = "EXPERIENCE THE NEW REALITY"
    content= "There is currently a fundamental change happening to the industry in the way we build, deploy and mange applications and websites. If your not ready for it your systems and services will quickly be left behind. Have you moved away from the monolithic server build out mindset? Is your application or website running in a POD? Is your application or website running in a containerized cluster? Is your application or website running serverless? Does your application or website deployment span data centers and systems all over the world? Do you know what Kubernetes is? If you anwsered NO to any or all of these questions, you are already falling way behind."
    btn = true
    btnText="More About Leroy A. Baynum Jr."
    btnURL="#about"

    # call to action
    [params.cta]
    enable = true
    title = "A truly great person with incredible knowledge that is fantastic to work with!"
    content = "- Scott Recor, Application Adminitrator IV, Ferguson Enterprises Inc.  (2018)"
    btnURL = "#contact-us"
    btnText = "Contact Leroy Now"

    # counter
    [params.counter]
    enable = true
    bgImage = "images/backgrounds/bg-1.jpg"
        [[params.counter.counterItem]]
        title = "Happy Clients"
        icon = "tf-ion-android-happy"
        count = "320"

        [[params.counter.counterItem]]
        title = "Projects completed"
        icon = "tf-ion-archive"
        count = "565"

        [[params.counter.counterItem]]
        title = "Positive feedback"
        icon = "tf-ion-thumbsup"
        count = "95"

        [[params.counter.counterItem]]
        title = "Cups of Coffee"
        icon = "tf-ion-coffee"
        count = "2500"

    # footer
    [params.footer]
        copyright = "Leroy A. Baynum Jr."
        copyrightURL = "https://leroy.baynum.net"

        # social Icons
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-facebook"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-twitter"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-google-outline"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-youtube"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-linkedin"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-dribbble-outline"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-pinterest-outline"
        url = "#"
